---
/deutschland/online_fgo:
    ros__parameters:
      use_sim_time: true
      GNSSFGO:
        verbose: false
        useIMUAsTimeReference: false
        bufferSize: 10
        optFrequency: 10 #in Hz
        calcErrorOnOpt: true
        cleanIMUonInit: true    # set this flag to clean the imu data before the timestamp of the initializing state
        useHeaderTimestamp: true
        #pubPoseVel: true
        #pubFGOState: true
        #pubPVTError: true
        #pubTimer: true
        #msg_lower_bound: 5000000 # 5 ms

        Initialization:
          initSigmaX: [ 2., 2., 2., 1., 1., 2. ] #first 3 for Rot in degree, other for translation in m
          initSigmaV: [ 1., 1., 1. ]
          initSigmaW: [ 0.05, 0.05, 0.05]
          initSigmaB: [ 0.5, 0.5, 0.5, 0.05, 0.05, 0.05] #first for b_a, second for b_g in degree
          initSigmaC: [ 1000., 10. ] #cb in m, cd in m/s

        IMUPreintegrator:
          accelerometerSigma: 0.008077134407821842 #3.9939570888238808e-04 #8e-4 # 8e-4
          integrationSigma: 1e-4 # 1e-4
          gyroscopeSigma: 0.0006939335887264338 #1.5636343949698187e-05   #52e-4 # 52e-5
          biasAccSigma: 4e-4 # 4e-4
          biasOmegaSigma: 87e-5 # 87e-5
          biasAccOmegaInt: 0.00001 # 0.00001

        Graph:
          IMUMeasurementFrequency: 200
          useGPPriorFactor: true
          gpType: 'WNOA'  # 'WNOA'
          useGPInterpolatedFactor: true

          AutoDiffNormalFactor: true
          AutoDiffGPInterpolatedFactor: true
          AutoDiffGPMotionPriorFactor: true
          GPInterpolatedFactorCalcJacobian: false

          StateMeasSyncUpperBound: 0.03
          StateMeasSyncLowerBound: -0.03
          useMMFactor: false
          useConstDriftFactor: false

          constDriftStd: 0.5
          constBiasStd: .1
          motionModelStd: 1.
          angularRateStd: 0.05
          magnetometerStd: 0.01

          NoOptimizationWhileNoMeasurement: true
          NoOptimizationNearZeroVelocity: true
          VoteNearZeroVelocity: 0.2  # 20%

        VehicleParameters:
          transIMUToReference: [ 0.365, -0.627, -0.2085 ] # [0.0, 0.0, 0.0]
          rotIMUToReference: [1., 0., 0., 0., 1., 0., 0., 0., 1.]
          #transIMUToReference: [ 0., 0., -0.36 ]  #ca
          #rotIMUToReference: [ 1., 0., 0., 0., 1., 0., 0., 0., 1. ]
          transIMUToGNSSAnt1: [ 0.365, -0.627, -0.2085 ] # [0.0, 0.0, 0.0]
          transIMUToGNSSAnt2: [ -0.11, 0.49, -0.2085 ] # [0.0, 0.0, 0.0]

          transIMUToLiDAR: [0.301411, 0., -0.0596]
          transIMUToCorrevit: [-1.5, 0., 1.2]
          #transIMUToCorrevit: [0., 0., 0.]
          rotIMUToLiDAR: [1., 0., 0., 0., -1., 0., 0., 0., -1. ]
          #transIMUToLiDAR: [ 0., 0., 0. ]  # ca
          #rotIMUToLiDAR: [ 1., 0., 0., 0., 1., 0., 0., 0., 1. ]

        Integrators: ["IRTPVALCIntegrator", "UbloxLCIntegrator", "CorrevitIntegrator"]   # ["UbloxIntegrator", "CorrevitIntegrator", "GNSSTCIntegrator", "LIOIntegrator"]

        Optimizer:
          #undefined, BatchFixedLag, IncrementalFixedLag
          smootherType: 'IncrementalFixedLag'
          smootherLag: 1. #marginalization threshhold
          #QcGPWNOJInterpolator: 1000.
          #QcGPWNOJMotionPrior: 10000.
          QcGPWNOJInterpolatorFull: [ 1000., 1000., 1000., 1000., 1000., 1000. ]
          QcGPWNOJMotionPriorFull: [ 10000., 10000., 10000., 10000., 10000., 10000. ]
          #QcGPWNOAInterpolator: 0.5
          #QcGPWNOAMotionPrior: 0.5
          QcGPWNOAInterpolatorFull: [ 0.5, 0.5, 0.5, 0.5, 0.5, 0.5 ]
          QcGPWNOAMotionPriorFull: [ 0.5, 0.5, 0.5, 0.5, 0.5, 0.5 ]
